- hosts: webservers
  tasks:
  - name: Copy deployment file to k8s master
    copy:
      src: deployment.yaml
      dest: /root/xyz_k8s_manifest/
  - name: Create New k8s objects
    command: "{{item}}"
    with_items: 
    - "kubectl apply -f /root/xyz_k8s_manifest/deployment.yaml"
    - "kubectl set image deployments/xyz-tech-frontend xyz-tech=sathiz/{{JOB_NAME}}:{{BUILD_NUMBER}} -n xyz-tech"