apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-tech-frontend
spec:
  selector:
    matchLabels:
      app: xyz-tech
  template:
    metadata:
      labels:
        app: xyz-tech
    spec:
      containers:
      - name: xyz-tech
        image: sathiz/$JOB_NAME:$BUILD_NUMBER
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
  replicas: 1

---

apiVersion: v1
kind: Service
metadata:
  name: xyz-tech-frontend
  labels:
    app: xyz-tech
spec:
  selector:
    app: xyz-tech
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31707
    protocol: TCP


