apiVersion: apps/v1
kind: Deployment
metadata:
  name: xyz-tech-frontend
  namespace: xyz-tech
spec:
  selector:
    matchLabels:
      app: xyz-tech
  template:
    metadata:
      labels:
        app: xyz-tech
    spec:
      containers:
      - name: xyz-tech
        image: sathiz/$JOB_NAME:$BUILD_NUMBER
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
  replicas: 1

---

apiVersion: v1
kind: Service
metadata:
  name: xyz-tech-service
  namespace: xyz-tech  
  labels:
    app: xyz-tech
spec:
  selector:
    app: xyz-tech
  type: NodePort
  ports:
  - port: 8080
    nodePort: 31707
    protocol: TCP

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: xyz-tech-hpa
  namespace: xyz-tech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: xyz-tech
  minReplicas: 1
  maxReplicas: 7
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10